OBCA001:
  sublocation: Ocean Beach
  city: San Francisco
  state: California
  country: USA
  iso_country_code: US

GGCA001:
  sublocation: Golden Gate Park
  city: San Francisco
  state: California
  country: USA
  iso_country_code: US

DTLA001:
  sublocation: Downtown
  city: Los Angeles
  state: California
  country: USA
  iso_country_code: US

OVHW001:
  sublocation: Hollywood
  city: Los Angeles
  state: California
  country: USA
  iso_country_code: US

SMOB001:
  sublocation: Santa Monica Beach
  city: Los Angeles
  state: California
  country: USA
  iso_country_code: US



