OBCA001:
  sublocation: Ocean Beach
  city: San Francisco
  state: California
  country: USA
  iso_country_code: US

GGCA001:
  sublocation: Golden Gate Park
  city: San Francisco
  state: California
  country: USA
  iso_country_code: US

DTLA001:
  sublocation: Downtown
  city: Los Angeles
  state: California
  country: USA
  iso_country_code: US

OVHW001:
  sublocation: Hollywood
  city: Los Angeles
  state: California
  country: USA
  iso_country_code: US

SMOB001:
  sublocation: Santa Monica Beach
  city: Los Angeles
  state: California
  country: USA
  iso_country_code: US

HLIB001:
  sublocation: The Huntington Library
  city: Los Angeles
  state: California
  country: USA
  iso_country_code: US

WESC001:
  sublocation: Westfield Century City
  city: Los Angeles
  state: California
  country: USA
  iso_country_code: US

WADC001:
  sublocation: Walt Disney Concert Hall
  city: Los Angeles
  state: California
  country: USA
  iso_country_code: US

MTAM001:
  sublocation: Mount Tamalpais
  city: Mill Valley
  state: California
  country: USA
  iso_country_code: US






