theetr1n1ty:
  full_name: Trinity Woodward
  ig_handle: "@theetr1n1ty"
  sex: Female

janedoe:
  full_name: Jane Doe
  ig_handle: "@janedoe"
  sex: Female

johndoe:
  full_name: John Doe
  ig_handle: "@johndoe"
  sex: Male
