theetr1n1ty:
  full_name: Trinity Woodward
  ig_handle: "@theetr1n1ty"
  sex: Female

ubaidfam:
  full_name: Ubaid Family
  ig_handle: "@ubaidrahman87"
  sex: Male

johndoe:
  full_name: John Doe
  ig_handle: "@johndoe"
  sex: Male
