theetr1n1ty:
  full_name: Trinity Woodward
  ig_handle: "@theetr1n1ty"
  sex: Female

ubaidfam:
  full_name: Ubaid Family
  ig_handle: "@ubaidrahman87"
  sex: Male

kerielle777:
  full_name: Keri
  ig_handle: "@kerielle777"
  sex: Female

vallady:
  full_name: Valentina Reneff-Olson
  ig_handle: "@vallady"
  sex: Female

casadilla1121:
  full_name: Cassidy Herndon
  ig_handle: "@casadilla1121"
  sex: Female
